name: wheels

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: deps
        run: python -m pip install -U pip wheel setuptools twine

      - name: wheel
        run: |
          python setup.py bdist_wheel

      - name: auditwheel
        if: contains(matrix.os, 'ubuntu')
        run: |
          python -m pip install -U auditwheel
          python -m auditwheel repair dist/*.whl
          rm -rf dist && mv wheelhouse dist

      - name: publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*
